### ISSUE TITLE
Feature: Limit user pannning to a certain max extent

### ISSUE THREAD

**Issue by pauldendulk** [itinero/ui#1]
In case the dataset covers a limited area you might want limit the users pan/zoom to that area.

One possible solution is to limit the entire mapview to this max extent. A problem with this approach is that if you pan to the edge and the zoom out one level (straight up), part of the visible map extent will be outside of the max extent. You could counter this displacing the map extent so that it is within the max extent but this is probably not a great user experience.

An alternatieve is to limit just the center of the map to stay within the max extent. When zooming straight the center of the map extent will still be within the max extent. But part of the map will be visible outside the max extent. How to deal with that:
- Just leave it as the background color and accept it
- Use an alternative data layer for context 
- Include the area that fallls outside the max extent but within the visible extent in the prepared dataset. What makes this more complicated is that this area is different for each zoom level. The more zoomed out the larger the area.

Here is different solution implemented in leaflet:
https://www.mapbox.com/mapbox.js/example/v1.0.0/maxbounds/
- zooming out is limited to a certain level
- A large area outside the target area is visible. This might not suit our scenario. It's an option.
- panning is not made impossible, but the map pans back after mouse-up.

**Comment by xivk** [comment]
Let's go for the simple solution first, center of the map withing extent but keep in mind more advanced scenario's when writing this code.

**Comment by pauldendulk** [comment]
`RestrictPanMode.KeepCenterWithinExtents` has been implemented and there are no complications.

`RestrictPanMode.KeepViewportWithinExtents` has been implemented. This mode is not applicable when the Map.Envelope does not span the full viewport. So the code checks this and does not restrict zoom in that case. This is checked separately for the horizontal and vertical directions so that there can be situations where horizontal panning is restricted but not vertical and vice versa.

`RestrictZoomMode.KeepWithinResolutions` is an option to restrict zooming in or out too much. 

With `RestrictZoomMode.KeepWithinResolutionsAndAlwaysFillViewport` it is possible to also prevent the user from zooming out to a level where the map does not span the viewport. When this is used in combination with `RestrictPanMode.KeepViewportWithinExtents` the full viewport is always fully covered by the map.

Complications:
1. When the 'map-spans-viewport-level' is more zoomed-in than the 'most-zoomed-in-level'  things become weird. The configuration is impossible. Possibly we should treat  'the map spans the viewport' as the most zoomed-in level in that case. In that case the map will be fixed on that zoom level. Alternatively we could stop restricting. Downside is no guarantee of ...AlwaysFillViewport
2. The most zoomed-in level is where the tiles show optimal. As a user I would like to be able to zoom-in more than that and blow up those at least one level more. The default should be perhaps go one step further.

**Comment by pauldendulk** [comment]
To fix complication 1 the AlwaysFillViewport part is skipped when the 'map-spans-viewport-level' is more zoomed-in than the 'most-zoomed-in-level'.

**Comment by pauldendulk** [comment]
To fix complication 1 we divide by two when determinin the ResolutionExtremes based on the Map.Resolutions.

**Comment by pauldendulk** [comment]
Ready for testing
